import React from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Atom, Zap, Wind, Activity } from 'lucide-react';

const SubstrateProperty = ({ icon: Icon, name, symbol, description }) => (
  <div className="p-4 rounded-sm bg-muted/20 border border-border/50">
    <div className="flex items-center gap-3 mb-2">
      <div className="w-10 h-10 bg-primary/10 border border-primary/50 rounded-sm flex items-center justify-center">
        <Icon className="w-5 h-5 text-primary" />
      </div>
      <div>
        <p className="font-semibold text-sm">{name}</p>
        <p className="text-xs font-mono text-primary">{symbol}</p>
      </div>
    </div>
    <p className="text-xs text-muted-foreground">{description}</p>
  </div>
);

export const SubstrateInfoModal = ({ open, onClose }) => {
  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-[800px] max-h-[90vh] overflow-y-auto bg-card/95 backdrop-blur-xl border-border/50" data-testid="substrate-info-modal">
        <DialogHeader>
          <DialogTitle className="text-3xl font-bold tracking-tight uppercase mb-2" style={{ fontFamily: 'Rajdhani, sans-serif' }}>
            QMRT Substrate Physics
          </DialogTitle>
          <DialogDescription className="text-sm text-muted-foreground">
            Quark Medium Relativity Theory - The Authoritative Physical Foundation. Learn about the four substrate properties and death-world scaling.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6 py-4">
          {/* Introduction */}
          <div className="p-6 rounded-sm bg-primary/10 border border-primary/50">
            <h3 className="font-semibold mb-2">Substrate-Based Reality</h3>
            <p className="text-sm text-muted-foreground leading-relaxed">
              QMRT posits that all physical phenomena emerge from interactions within a fundamental substrate 
              characterized by four core properties. Unlike traditional physics models that treat space as empty, 
              QMRT views the universe as a dynamic medium where density, tension, torsion, and coherence phase 
              drive all emergent forces, particle structures, and biological processes.
            </p>
          </div>

          {/* Four Pillars */}
          <div>
            <h3 className="text-sm font-mono uppercase tracking-widest text-muted-foreground mb-4">
              The Four Substrate Properties
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <SubstrateProperty
                icon={Atom}
                name="Density"
                symbol="ρΞ (rho-Xi)"
                description="Determines inertia and gravitational-like behavior. Higher density creates stronger gravitational wells and matter concentration."
              />
              <SubstrateProperty
                icon={Zap}
                name="Tension"
                symbol="TΞ (T-Xi)"
                description="Governs wave speed, electromagnetic analogs, and local dynamic responsiveness. Controls energy propagation through the substrate."
              />
              <SubstrateProperty
                icon={Wind}
                name="Torsion"
                symbol="τΞ (tau-Xi)"
                description="Introduces rotational degrees of freedom analogous to spin and magnetic alignment. Defines stability conditions for particle-like structures."
              />
              <SubstrateProperty
                icon={Activity}
                name="Coherence Phase"
                symbol="ΦΞ (Phi-Xi)"
                description="Governs interference, quantum phenomena, biological signaling, and consciousness potential. The foundation for complex emergence."
              />
            </div>
          </div>

          {/* Wave Equations */}
          <div className="p-6 rounded-sm bg-card/40 backdrop-blur-md border border-border/50">
            <h3 className="font-semibold mb-3">Coupled Substrate Dynamics</h3>
            <p className="text-sm text-muted-foreground mb-4">
              Worlds are generated by evolving coupled wave equations that describe how these four properties 
              interact and propagate through the substrate:
            </p>
            <div className="space-y-2 font-mono text-xs text-muted-foreground bg-muted/20 p-4 rounded-sm">
              <p>∂²(ΦΞ)/∂t² = A_φ ∇²(ΦΞ) + B_φ ∇²(ρΞ) + C_φ ∇²(TΞ)</p>
              <p>∂²(ρΞ)/∂t² = A_ρ ∇²(ρΞ) + B_ρ ∇²(TΞ)</p>
              <p>∂²(TΞ)/∂t² = A_T ∇²(TΞ) + B_T ∇²(ρΞ)</p>
              <p>∂²(τΞ)/∂t² = A_τ ∇²(τΞ) + curl_terms</p>
            </div>
          </div>

          {/* Death-World Scaling */}
          <div>
            <h3 className="text-sm font-mono uppercase tracking-widest text-muted-foreground mb-4">
              Death-World Scaling System
            </h3>
            <div className="space-y-3">
              <div className="p-4 rounded-sm bg-green-500/10 border border-green-500/50">
                <div className="flex items-center justify-between mb-2">
                  <span className="font-semibold text-sm text-green-500">Levels 1-3: Sanctuary Worlds</span>
                  <span className="font-mono text-xs text-muted-foreground">Low difficulty</span>
                </div>
                <p className="text-xs text-muted-foreground">Minimal substrate perturbations, stable coherence, low environmental stress</p>
              </div>
              
              <div className="p-4 rounded-sm bg-blue-500/10 border border-blue-500/50">
                <div className="flex items-center justify-between mb-2">
                  <span className="font-semibold text-sm text-blue-500">Level 10: Earth-Class World</span>
                  <span className="font-mono text-xs text-muted-foreground">Reference standard</span>
                </div>
                <p className="text-xs text-muted-foreground">Balanced substrate parameters, moderate torsion, optimal biological viability</p>
              </div>
              
              <div className="p-4 rounded-sm bg-red-500/10 border border-red-500/50">
                <div className="flex items-center justify-between mb-2">
                  <span className="font-semibold text-sm text-red-500">Levels 11-15: Death Worlds</span>
                  <span className="font-mono text-xs text-muted-foreground">Extreme difficulty</span>
                </div>
                <p className="text-xs text-muted-foreground">Extreme substrate gradients, high torsion chaos, unstable coherence, apex qualification enabled</p>
              </div>
            </div>
          </div>

          {/* Future Systems */}
          <div className="p-6 rounded-sm bg-secondary/10 border border-secondary/50">
            <h3 className="font-semibold mb-3">Future Development Phases</h3>
            <div className="space-y-2 text-sm text-muted-foreground">
              <div className="flex items-center gap-2">
                <span className="font-mono text-xs px-2 py-0.5 rounded bg-secondary/20 border border-secondary/50">Phase B</span>
                <span>Ecological & Evolutionary Simulation</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="font-mono text-xs px-2 py-0.5 rounded bg-secondary/20 border border-secondary/50">Phase C</span>
                <span>Apex Qualification & Hidden Lineage Tracking</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="font-mono text-xs px-2 py-0.5 rounded bg-secondary/20 border border-secondary/50">Phase C</span>
                <span>Civilization Emergence Systems</span>
              </div>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};
